# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 1 webpage a day
email: hi@nto.lu
description: > # this means to ignore newlines until "baseurl:"
  The adventure of one guy building 1 webpage a day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://1wpad.nto.lu" # the base hostname & protocol for your site
permalink: /days/:title/

# Build settings
markdown: kramdown
